owner: makedeb
repo: status

sites:
  - name: makedeb Homepage
    url: https://www.makedeb.org
  - name: makedeb Docs
    url: https://docs.makedeb.org
  - name: makedeb Package Repository
    url: https://mpr.makedeb.org
  - name: makedeb ProGet Instance
    url: https://proget.makedeb.org

status-website:
  cname: status.makedeb.org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "makedeb Statuspage"
  navbar:
    - title: Homepage
      href: https://makedeb.org
    - title: Docs
      href: https://docs.makedeb.org
    - title: MPR
      href: https://mpr.makedeb.org
    - title: News
      href: https://makedeb.org/news
    - title: Donate
      href: https://makedeb.org/donate
