owner: makedeb
repo: status

sites:
  - name: makedeb Homepage
    url: https://www.makedeb.org
  - name: makedeb Docs
    url: https://docs.makedeb.org
  - name: makedeb Package Repository
    url: https://mpr.makedeb.org
  - name: makedeb ProGet Instance
    url: https://proget.makedeb.org
  - name: makedeb Minecraft Server
    check: "tcp-ping"
    url: minecraft.makedeb.org
    port: 25565

status-website:
  cname: status.makedeb.org
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "makedeb Statuspage"
  navbar:
    - title: Homepage
      href: https://makedeb.org
    - title: Docs
      href: https://docs.makedeb.org
    - title: MPR
      href: https://mpr.makedeb.org
    - title: News
      href: https://makedeb.org/news
    - title: Donate
      href: https://makedeb.org/donate

workflowSchedule:
  graphs: "*/5 0,1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24 * * *"
  responseTime: "*/5 0,1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/5 0,1,2,3,4,5,6,7,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24 * * *"
